-- Run these SQL commands in Supabase SQL editor (Dashboard -> SQL -> New Query) to create tables used by the app
create table if not exists staff (
  id text primary key,
  name text,
  phone text,
  role text,
  hourly int,
  photo text,
  created_at timestamptz default now()
);

create table if not exists attendance (
  id text primary key,
  staffId text references staff(id),
  type text,
  time timestamptz,
  created_at timestamptz default now()
);

create table if not exists payments (
  id text primary key,
  staffId text references staff(id),
  amount numeric,
  note text,
  time timestamptz,
  created_at timestamptz default now()
);

create table if not exists complaints (
  id text primary key,
  staffId text references staff(id),
  text text,
  time timestamptz,
  created_at timestamptz default now()
);

create table if not exists uploads (
  id text primary key,
  staffId text references staff(id),
  note text,
  url text,
  time timestamptz,
  created_at timestamptz default now()
);


-- RBAC: users table (if not exists) and sample roles
CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text UNIQUE,
  password text,
  role text DEFAULT 'staff',
  job_role text,
  staff_code text,
  phone text,
  created_at timestamptz DEFAULT now()
);

-- Seed example superadmin (do not store plain password in production)
INSERT INTO users (name,email,password,role,staff_code) VALUES ('Golu','owner@example.com','supersecret','superadmin','SD-000') ON CONFLICT DO NOTHING;
